version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    images: nginx:42
    ports:
      - "443:443"
    depends_on:
      - wordpress
    env_file:
      - .env
    volumes:
     - wordpress:/var/www/html
    restart: always
    networks:
      - inception

  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    container_name: mariadb
    env_file:
      - .env
    image: mariadb:42
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql/
    restart: always
    networks:
      - inception


  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress:42
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress:/war/www/html
    networks:
      - inception
    restart: always