version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx:42
    ports:
      - "443:443"
    depends_on:
      - wordpress
    env_file:
      - .env
    volumes:
     - wordpress:/var/www/html
    restart: always
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    env_file:
      - .env
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
    image: mariadb:42
    ports:
      - "33060:3306"
    volumes:
      - mariadb:/var/lib/mysql/
    restart: always
    networks:
      - inception


  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress:42
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always

volumes:
  wordpress:
  mariadb:

networks:
  inception:
    name: inception
    driver: bridge
